version: "2"
plugins:
  duplication:
    enabled: false
    config:
      languages:
        java:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
      channel: "10.13.0"
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
        - "java-clone"
        - "java-design"
        - "java-empty"
        - "java-finalizers"
        - "java-imports"
        - "java-migrating"
        - "java-optimizations"
        - "java-strictexception"
        - "java-strings"
        - "java-sunsecure"
        - "java-typeresolution"
        - "java-unnecessary"
        - "java-unusedcode"
    checks:
      AvoidCatchingGenericException:
        enabled: false
      AvoidInstantiatingObjectsInLoops:
        enabled: false
      AvoidSynchronizedAtMethodLevel:
        enabled: false
      AvoidThrowingRawExceptionTypes:
        enabled: false
      DataClass:
        enabled: false
      UselessParentheses:
        enabled: false
      MethodArgumentCouldBeFinal:
        enabled: false
      LocalVariableCouldBeFinal:
        enabled: false
      PrematureDeclaration:
        enabled: false
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "21"
    checks:
      squid:S00112:
        enabled: false
checks:
  argument-count:
    config:
      threshold: 6 # No more than 6 arguments
  method-lines:
    config:
      threshold: 80 # No more than 2 screens
  method-complexity:
    config:
      threshold: 15 # We are Russian hackers!
  similar-code:
    config:
      threshold: 60 # Sometimes it is not so similar
  identical-code:
    config:
      threshold: 60 # Nope, not a duplicate
  return-statements:
    config:
      threshold: 10 # Have pattern-matching-like code
exclude_patterns:
  - "**/*.svg"
  - "src/test/"
  - "src/main/java/ru/vk/itmo/test/reference/"
